"use client"
import {useState,useEffect} from "react"
import ThemeCarousel from "../components/ThemeCarousel"
import CameraScreen from "../components/CameraScreen"
import {generatePhoto} from "../lib/generate"
import {addJob} from "../store/queue"

export default function Home() {

const [screen,setScreen]=useState("idle")

const [selectedTheme,setSelectedTheme]=useState("")
const [capturedImage,setCapturedImage]=useState("")
const [generatedImage,setGeneratedImage]=useState("")
const [isGenerating,setGenerating]=useState(false)
const [queueNumber,setQueueNumber]=useState(0)
const [resetTimer,setResetTimer]=useState(8)

useEffect(()=>{

if(
screen!=="result"
){

return

}

setResetTimer(8)

const timer=
setInterval(()=>{

setResetTimer(
(prev)=>{

if(
prev<=1
){

clearInterval(
timer)

setCapturedImage("")

setGeneratedImage("")

setSelectedTheme("")

setGenerating(false)

setScreen("idle")

return 8

}

return prev-1

})

},1000)

return()=>{

clearInterval(
timer)

}

},[
screen
])

if(
isGenerating
){

return(

<main
className="
h-screen

bg-black

text-white

flex

flex-col

justify-center

items-center
"
>

<h1
className="
text-5xl

font-bold
"
>

GENERATING

</h1>
<p
className="
mt-4

text-white/40
"
>

QUEUE

—

{queueNumber}

</p>
<p
className="
mt-4

text-gray-500
"
>

Creating cinematic photo...

</p>

<div
className="
mt-10

w-[300px]

h-[4px]

bg-white/10

rounded-full

overflow-hidden
"
>

<div
className="
h-full

w-[60%]

bg-white

animate-pulse
"
/>

</div>

</main>

)

}

if(
screen==="camera"
){

return(

<CameraScreen
    onComplete={() => {
        setScreen("home");
    }}
/>

)

}

if(
screen==="result"
){

return(

<main
className="
h-screen
bg-black
text-white
flex
flex-col
justify-center
items-center
px-10
"
>

<h1
className="
text-6xl
font-black
mb-10
"
>

HASILMU

</h1>

<p
className="
mb-8

tracking-[0.4em]

text-gray-500
"
>

THEME

—

{selectedTheme}

</p>

<div
className="
relative
bg-gradient-to-b

from-white/5

to-transparent

p-3
w-[520px]

rounded-[40px]

overflow-hidden

border

border-white/10

shadow-[0_0_100px_rgba(255,255,255,0.08)]
"
>

<img

src={generatedImage}

alt="hasil"

className="
w-full
object-cover
"

/>

</div>

<div
className="
mt-8
flex
gap-5
"
>

<button

onClick={()=>{

const a=
document.createElement(
"a"
)

a.href=
generatedImage

a.download=
"ai-photobooth.jpg"

a.click()

}}

className="
px-10
py-4

bg-white

text-black

rounded-full

font-bold
"
>

DOWNLOAD

</button>

<button

className="
px-10
py-4

border

rounded-full
"

>

QR SHARE

</button>

<button

onClick={()=>{

setCapturedImage("")
setGeneratedImage("")
setSelectedTheme("")
setQueueNumber(0)
setScreen("theme")

}}

className="
px-10
py-4

border

rounded-full
"
>

BUAT LAGI

</button>

</div>

<p
className="
mt-8

text-white/40
"
>

Reset otomatis dalam

{resetTimer}

detik

</p>

</main>

)

}
if(screen==="theme"){
return(

<main
className="
h-screen
bg-black
text-white
flex
flex-col
justify-center
items-center
"
>

<h1
className="
text-5xl
font-bold
"
>
PILIH TEMA
</h1>

<ThemeCarousel
onSelect={(theme)=>{

setSelectedTheme(theme)

setScreen("camera")

}}
/>

</main>

)
}

return(

<main
className="
h-screen
bg-black
text-white
flex
justify-center
items-center
"
>

<div className="text-center">

<h1
className="
text-6xl
font-bold
"
>
AI PHOTOBOOTH
</h1>

<p
className="
mt-4
text-gray-400
"
>
Cinematic Experience
</p>

<button
onClick={()=>
setScreen("theme")
}

className="
mt-10
px-10
py-4
rounded-full
bg-white
text-black
font-semibold
"
>

TAP TO START

</button>

</div>
<p
className="
absolute

bottom-10

text-sm

text-white/30
"
>

Generated by AI Photobooth

</p>
</main>

)

}